import {
  AdminActionType,
  NotificationType,
  ReportStatus,
  ReportableType,
  TrackPrivacy,
  TrackStatus,
  UserRole,
} from '@wavestream/shared';

export const DEMO_LISTENER_PASSWORD = 'DemoPass123!';

// ---------------------------------------------------------------------------
// Interfaces
// ---------------------------------------------------------------------------

export interface SeedPalette {
  background: string;
  foreground: string;
  accent: string;
}

export interface SeedUserSpec {
  username: string;
  email: string;
  displayName: string;
  role: UserRole;
  bio: string;
  location: string;
  websiteUrl?: string;
  avatarPalette: SeedPalette;
  bannerPalette: SeedPalette;
}

export interface SeedTrackSpec {
  slug: string;
  artistUsername: string;
  title: string;
  description: string;
  genre: string;
  tags: string[];
  privacy: TrackPrivacy;
  status: TrackStatus;
  allowDownloads: boolean;
  commentsEnabled: boolean;
  hiddenReason?: string;
  daysAgo: number;
  durationSeconds: number;
  baseFrequency: number;
  pulseFrequency: number;
  palette: SeedPalette;
}

export interface SeedPlaylistSpec {
  slug: string;
  ownerUsername: string;
  title: string;
  description: string;
  isPublic: boolean;
  trackSlugs: string[];
  daysAgo: number;
  palette: SeedPalette;
}

export interface SeedCommentSpec {
  key: string;
  username: string;
  trackSlug: string;
  body: string;
  timestampSeconds?: number;
  parentKey?: string;
  hidden?: boolean;
}

export interface SeedReportSpec {
  reporterUsername: string;
  reportableType: ReportableType;
  targetKey: string;
  reason: string;
  details?: string;
  status: ReportStatus;
  resolvedByAdmin?: boolean;
  resolutionNote?: string;
}

export interface SeedAuditLogSpec {
  action: AdminActionType;
  entityType: string;
  entityKey: string;
  details?: Record<string, unknown>;
}

export interface SeedNotificationSpec {
  username: string;
  type: NotificationType;
  data: Record<string, unknown>;
}

// ---------------------------------------------------------------------------
// Genres
// ---------------------------------------------------------------------------

export const SEED_GENRES = [
  'Electronic',
  'Lo-fi',
  'House',
  'Ambient',
  'Indie',
  'Hip-Hop',
  'R&B',
  'Jazz',
  'Soul',
  'Experimental',
  'Pop',
  'Future Bass',
  'Drum & Bass',
  'Techno',
];

// ---------------------------------------------------------------------------
// Users — 5 original creators + 5 new creators + 20 listeners = 30 total
// ---------------------------------------------------------------------------

export const SEED_USERS: SeedUserSpec[] = [
  // ── Original 5 creators ────────────────────────────────────────────────
  {
    username: 'solis-kim',
    email: 'solis@wavestream.demo',
    displayName: 'Solis Kim',
    role: UserRole.CREATOR,
    bio: 'Builds nocturnal synth sketches for long train rides and coding sprints.',
    location: 'Bangkok, Thailand',
    websiteUrl: 'https://wavestream.demo/solis-kim',
    avatarPalette: { background: '#0b132b', foreground: '#f4f1de', accent: '#ff7b54' },
    bannerPalette: { background: '#102542', foreground: '#f8f9fa', accent: '#f87060' },
  },
  {
    username: 'aria-voss',
    email: 'aria@wavestream.demo',
    displayName: 'Aria Voss',
    role: UserRole.CREATOR,
    bio: 'Warm tape textures, sunrise guitar loops, and voice memo details.',
    location: 'Berlin, Germany',
    websiteUrl: 'https://wavestream.demo/aria-voss',
    avatarPalette: { background: '#14342b', foreground: '#fefae0', accent: '#f4a261' },
    bannerPalette: { background: '#1d3557', foreground: '#f1faee', accent: '#f4a261' },
  },
  {
    username: 'miko-lane',
    email: 'miko@wavestream.demo',
    displayName: 'Miko Lane',
    role: UserRole.CREATOR,
    bio: 'Club percussion, polished basslines, and quick-loop DJ ideas.',
    location: 'Ho Chi Minh City, Vietnam',
    websiteUrl: 'https://wavestream.demo/miko-lane',
    avatarPalette: { background: '#201e43', foreground: '#fff8e8', accent: '#f97316' },
    bannerPalette: { background: '#1b1f3b', foreground: '#f8edeb', accent: '#ffb703' },
  },
  {
    username: 'noa-river',
    email: 'noa@wavestream.demo',
    displayName: 'Noa River',
    role: UserRole.CREATOR,
    bio: 'Quiet ambient builds and low-end R&B demos with lots of negative space.',
    location: 'Seoul, South Korea',
    websiteUrl: 'https://wavestream.demo/noa-river',
    avatarPalette: { background: '#1f2937', foreground: '#f9fafb', accent: '#38bdf8' },
    bannerPalette: { background: '#0f172a', foreground: '#e2e8f0', accent: '#22d3ee' },
  },
  {
    username: 'luka-bayne',
    email: 'luka@wavestream.demo',
    displayName: 'Luka Bayne',
    role: UserRole.CREATOR,
    bio: 'Indie hooks, broken-drum experiments, and rough-cut vocal toplines.',
    location: 'Lisbon, Portugal',
    websiteUrl: 'https://wavestream.demo/luka-bayne',
    avatarPalette: { background: '#2d1e2f', foreground: '#f7f7ff', accent: '#ff9f1c' },
    bannerPalette: { background: '#2b2d42', foreground: '#edf2f4', accent: '#ef476f' },
  },
  // ── New 5 creators ─────────────────────────────────────────────────────
  {
    username: 'zara-nash',
    email: 'zara@wavestream.demo',
    displayName: 'Zara Nash',
    role: UserRole.CREATOR,
    bio: 'Soul loops and neo-jazz fragments that drift between eras.',
    location: 'Lagos, Nigeria',
    websiteUrl: 'https://wavestream.demo/zara-nash',
    avatarPalette: { background: '#3d0000', foreground: '#fff3e0', accent: '#ff6b35' },
    bannerPalette: { background: '#1a0000', foreground: '#ffd6b0', accent: '#ff9800' },
  },
  {
    username: 'finn-oslo',
    email: 'finn@wavestream.demo',
    displayName: 'Finn Oslo',
    role: UserRole.CREATOR,
    bio: 'Glitchy IDM textures and field recordings from Nordic winters.',
    location: 'Oslo, Norway',
    websiteUrl: 'https://wavestream.demo/finn-oslo',
    avatarPalette: { background: '#0a1628', foreground: '#e8f4f8', accent: '#00bcd4' },
    bannerPalette: { background: '#0d1b2a', foreground: '#e0f2f7', accent: '#26c6da' },
  },
  {
    username: 'cleo-wave',
    email: 'cleo@wavestream.demo',
    displayName: 'Cleo Wave',
    role: UserRole.CREATOR,
    bio: 'Synth-pop hooks and bedroom indie with a wide-open mix.',
    location: 'Toronto, Canada',
    websiteUrl: 'https://wavestream.demo/cleo-wave',
    avatarPalette: { background: '#1a0033', foreground: '#f3e5ff', accent: '#b388ff' },
    bannerPalette: { background: '#12002a', foreground: '#ede7f6', accent: '#9c27b0' },
  },
  {
    username: 'riku-jin',
    email: 'riku@wavestream.demo',
    displayName: 'Riku Jin',
    role: UserRole.CREATOR,
    bio: 'Future bass drops and lo-fi trap beats — fast sketches, sharp ideas.',
    location: 'Tokyo, Japan',
    websiteUrl: 'https://wavestream.demo/riku-jin',
    avatarPalette: { background: '#001a33', foreground: '#e3f2fd', accent: '#2196f3' },
    bannerPalette: { background: '#000d1a', foreground: '#bbdefb', accent: '#1565c0' },
  },
  {
    username: 'sena-sol',
    email: 'sena@wavestream.demo',
    displayName: 'Sena Sol',
    role: UserRole.CREATOR,
    bio: 'Acoustic jazz sketches, neo-soul chord studies, and piano improvisations.',
    location: 'Accra, Ghana',
    websiteUrl: 'https://wavestream.demo/sena-sol',
    avatarPalette: { background: '#1b2200', foreground: '#f9fbe7', accent: '#c6e826' },
    bannerPalette: { background: '#0d1400', foreground: '#f0f4c3', accent: '#aed136' },
  },
  // ── Original 5 listeners ───────────────────────────────────────────────
  {
    username: 'ivy-hart',
    email: 'ivy@wavestream.demo',
    displayName: 'Ivy Hart',
    role: UserRole.LISTENER,
    bio: 'Playlist-heavy listener who bookmarks every late-night loop.',
    location: 'Singapore',
    avatarPalette: { background: '#264653', foreground: '#f1faee', accent: '#e9c46a' },
    bannerPalette: { background: '#1d3557', foreground: '#f1faee', accent: '#a8dadc' },
  },
  {
    username: 'dev-patel',
    email: 'dev@wavestream.demo',
    displayName: 'Dev Patel',
    role: UserRole.LISTENER,
    bio: 'Finds mixes for commute mode and keeps a deep queue of reposts.',
    location: 'London, United Kingdom',
    avatarPalette: { background: '#0f4c5c', foreground: '#edf6f9', accent: '#ffb703' },
    bannerPalette: { background: '#023047', foreground: '#edf6f9', accent: '#fb8500' },
  },
  {
    username: 'mia-tran',
    email: 'mia@wavestream.demo',
    displayName: 'Mia Tran',
    role: UserRole.LISTENER,
    bio: 'Searches for polished demos and drops timestamped notes on every find.',
    location: 'Da Nang, Vietnam',
    avatarPalette: { background: '#283618', foreground: '#fefae0', accent: '#dda15e' },
    bannerPalette: { background: '#606c38', foreground: '#fefae0', accent: '#bc6c25' },
  },
  {
    username: 'theo-cross',
    email: 'theo@wavestream.demo',
    displayName: 'Theo Cross',
    role: UserRole.LISTENER,
    bio: 'Front-row fan for house and bass edits, especially unfinished ones.',
    location: 'Melbourne, Australia',
    avatarPalette: { background: '#14213d', foreground: '#fefae0', accent: '#fca311' },
    bannerPalette: { background: '#003049', foreground: '#fdf0d5', accent: '#f77f00' },
  },
  {
    username: 'jules-park',
    email: 'jules@wavestream.demo',
    displayName: 'Jules Park',
    role: UserRole.LISTENER,
    bio: 'Collects mellow instrumentals for design reviews and long edits.',
    location: 'Taipei, Taiwan',
    avatarPalette: { background: '#3a0ca3', foreground: '#f8f9fa', accent: '#4cc9f0' },
    bannerPalette: { background: '#480ca8', foreground: '#f8f9fa', accent: '#f72585' },
  },
  // ── New 15 listeners ───────────────────────────────────────────────────
  {
    username: 'kai-brooks',
    email: 'kai@wavestream.demo',
    displayName: 'Kai Brooks',
    role: UserRole.LISTENER,
    bio: 'Late-night crate digger — finds underground gems before they trend.',
    location: 'Chicago, USA',
    avatarPalette: { background: '#212121', foreground: '#fafafa', accent: '#ff5722' },
    bannerPalette: { background: '#1a1a1a', foreground: '#f5f5f5', accent: '#ff7043' },
  },
  {
    username: 'luna-mar',
    email: 'luna@wavestream.demo',
    displayName: 'Luna Mar',
    role: UserRole.LISTENER,
    bio: 'Chases ambient and lo-fi for focus blocks and slow-morning routines.',
    location: 'Barcelona, Spain',
    avatarPalette: { background: '#001f3d', foreground: '#e8f4f8', accent: '#4fc3f7' },
    bannerPalette: { background: '#00152b', foreground: '#e1f5fe', accent: '#0288d1' },
  },
  {
    username: 'sam-reed',
    email: 'sam@wavestream.demo',
    displayName: 'Sam Reed',
    role: UserRole.LISTENER,
    bio: 'Film score enthusiast exploring electronic crossovers and abstract production.',
    location: 'Amsterdam, Netherlands',
    avatarPalette: { background: '#1b0000', foreground: '#fff3e0', accent: '#ef5350' },
    bannerPalette: { background: '#0d0000', foreground: '#fce4ec', accent: '#e53935' },
  },
  {
    username: 'alex-wu',
    email: 'alex@wavestream.demo',
    displayName: 'Alex Wu',
    role: UserRole.LISTENER,
    bio: 'Producer-curious listener, always analyzing how tracks are constructed.',
    location: 'Shanghai, China',
    avatarPalette: { background: '#0d2137', foreground: '#e8eaf6', accent: '#7986cb' },
    bannerPalette: { background: '#050e1f', foreground: '#e8eaf6', accent: '#5c6bc0' },
  },
  {
    username: 'priya-sen',
    email: 'priya@wavestream.demo',
    displayName: 'Priya Sen',
    role: UserRole.LISTENER,
    bio: 'Yoga-flow and meditation playlists curator. Ambient and jazz is home.',
    location: 'Mumbai, India',
    avatarPalette: { background: '#1a0026', foreground: '#f3e5f5', accent: '#ce93d8' },
    bannerPalette: { background: '#0d0018', foreground: '#e1bee7', accent: '#ab47bc' },
  },
  {
    username: 'omar-diaz',
    email: 'omar@wavestream.demo',
    displayName: 'Omar Diaz',
    role: UserRole.LISTENER,
    bio: 'Hip-hop head with a long memory and an ear for boom-bap detail.',
    location: 'Mexico City, Mexico',
    avatarPalette: { background: '#1a1200', foreground: '#fff8e1', accent: '#ffd54f' },
    bannerPalette: { background: '#0d0900', foreground: '#fffde7', accent: '#ffca28' },
  },
  {
    username: 'hana-kato',
    email: 'hana@wavestream.demo',
    displayName: 'Hana Kato',
    role: UserRole.LISTENER,
    bio: 'J-music crossover listener — city pop, future bass, and quiet electronic.',
    location: 'Osaka, Japan',
    avatarPalette: { background: '#001233', foreground: '#e0f7fa', accent: '#00acc1' },
    bannerPalette: { background: '#000d22', foreground: '#b2ebf2', accent: '#0097a7' },
  },
  {
    username: 'ben-flores',
    email: 'ben@wavestream.demo',
    displayName: 'Ben Flores',
    role: UserRole.LISTENER,
    bio: 'Club culture archivist — tracking house lineage from Chicago to global scenes.',
    location: 'São Paulo, Brazil',
    avatarPalette: { background: '#1a2600', foreground: '#f9fbe7', accent: '#8bc34a' },
    bannerPalette: { background: '#0d1900', foreground: '#f0f4c3', accent: '#689f38' },
  },
  {
    username: 'nadia-berg',
    email: 'nadia@wavestream.demo',
    displayName: 'Nadia Berg',
    role: UserRole.LISTENER,
    bio: "Indie and alternative explorer. If it sounds like it was recorded in a bedroom, she's in.",
    location: 'Stockholm, Sweden',
    avatarPalette: { background: '#002233', foreground: '#e8f5e9', accent: '#66bb6a' },
    bannerPalette: { background: '#001522', foreground: '#c8e6c9', accent: '#4caf50' },
  },
  {
    username: 'carlos-rey',
    email: 'carlos@wavestream.demo',
    displayName: 'Carlos Rey',
    role: UserRole.LISTENER,
    bio: 'Drums-first listener. Can hear a kick problem from three pages away.',
    location: 'Madrid, Spain',
    avatarPalette: { background: '#2a0010', foreground: '#fce4ec', accent: '#f48fb1' },
    bannerPalette: { background: '#1a0009', foreground: '#fce4ec', accent: '#f06292' },
  },
  {
    username: 'emi-lake',
    email: 'emi@wavestream.demo',
    displayName: 'Emi Lake',
    role: UserRole.LISTENER,
    bio: 'Finds a new ambient EP every week and archives them obsessively.',
    location: 'Vancouver, Canada',
    avatarPalette: { background: '#00192b', foreground: '#e8eaf6', accent: '#9fa8da' },
    bannerPalette: { background: '#000f1a', foreground: '#e8eaf6', accent: '#7986cb' },
  },
  {
    username: 'leo-hart',
    email: 'leo@wavestream.demo',
    displayName: 'Leo Hart',
    role: UserRole.LISTENER,
    bio: 'Electronic music journalist. Listens critically, recommends generously.',
    location: 'New York, USA',
    avatarPalette: { background: '#1a0d00', foreground: '#fff3e0', accent: '#ff9800' },
    bannerPalette: { background: '#0d0700', foreground: '#ffe0b2', accent: '#f57c00' },
  },
  {
    username: 'yui-chen',
    email: 'yui@wavestream.demo',
    displayName: 'Yui Chen',
    role: UserRole.LISTENER,
    bio: 'UI designer by day, downtempo DJ by night. Aesthetic first, always.',
    location: 'Shenzhen, China',
    avatarPalette: { background: '#1a001a', foreground: '#fce4ec', accent: '#f48fb1' },
    bannerPalette: { background: '#0d000d', foreground: '#fce4ec', accent: '#e91e63' },
  },
  {
    username: 'tobias-m',
    email: 'tobias@wavestream.demo',
    displayName: 'Tobias M.',
    role: UserRole.LISTENER,
    bio: 'Techno loyalist. Appreciates anything with a 4/4 kick and a story.',
    location: 'Frankfurt, Germany',
    avatarPalette: { background: '#111111', foreground: '#f5f5f5', accent: '#bdbdbd' },
    bannerPalette: { background: '#0a0a0a', foreground: '#eeeeee', accent: '#9e9e9e' },
  },
  {
    username: 'aisha-ko',
    email: 'aisha@wavestream.demo',
    displayName: 'Aisha Ko',
    role: UserRole.LISTENER,
    bio: 'Playlist architect. Sequences are her art form.',
    location: 'Cape Town, South Africa',
    avatarPalette: { background: '#002622', foreground: '#e0f2f1', accent: '#80cbc4' },
    bannerPalette: { background: '#001510', foreground: '#b2dfdb', accent: '#26a69a' },
  },
];

// ---------------------------------------------------------------------------
// Tracks — 17 original + 18 new = 35 total
// ---------------------------------------------------------------------------

export const SEED_TRACKS: SeedTrackSpec[] = [
  // ── Original 17 tracks ─────────────────────────────────────────────────
  {
    slug: 'midnight-static',
    artistUsername: 'solis-kim',
    title: 'Midnight Static',
    description:
      'A glossy midnight driver with clipped drums, slow-bloom pads, and a patient low end.',
    genre: 'Electronic',
    tags: ['analog', 'night-drive', 'synth'],
    privacy: TrackPrivacy.PUBLIC,
    status: TrackStatus.PUBLISHED,
    allowDownloads: true,
    commentsEnabled: true,
    daysAgo: 2,
    durationSeconds: 16,
    baseFrequency: 220,
    pulseFrequency: 2,
    palette: { background: '#0f172a', foreground: '#f8fafc', accent: '#fb7185' },
  },
  {
    slug: 'aurora-current',
    artistUsername: 'solis-kim',
    title: 'Aurora Current',
    description:
      'A longer electronic pulse with drifted harmonics, soft lift, and a steadier late-night glide.',
    genre: 'Electronic',
    tags: ['synth', 'drift', 'night-drive'],
    privacy: TrackPrivacy.PUBLIC,
    status: TrackStatus.PUBLISHED,
    allowDownloads: true,
    commentsEnabled: true,
    daysAgo: 0,
    durationSeconds: 32,
    baseFrequency: 208,
    pulseFrequency: 2.6,
    palette: { background: '#08111f', foreground: '#f8fbff', accent: '#38bdf8' },
  },
  {
    slug: 'balcony-sunrise',
    artistUsername: 'aria-voss',
    title: 'Balcony Sunrise',
    description: 'Tape-soft chords and brushed drums made for slow starts and second coffees.',
    genre: 'Lo-fi',
    tags: ['morning', 'study', 'tape'],
    privacy: TrackPrivacy.PUBLIC,
    status: TrackStatus.PUBLISHED,
    allowDownloads: true,
    commentsEnabled: true,
    daysAgo: 1,
    durationSeconds: 18,
    baseFrequency: 196,
    pulseFrequency: 2.5,
    palette: { background: '#1f2937', foreground: '#fef3c7', accent: '#fb923c' },
  },
  {
    slug: 'linen-hours',
    artistUsername: 'aria-voss',
    title: 'Linen Hours',
    description:
      'A softer lo-fi loop with brushed percussion, widened chords, and a little more room to breathe.',
    genre: 'Lo-fi',
    tags: ['study', 'tape', 'warm'],
    privacy: TrackPrivacy.PUBLIC,
    status: TrackStatus.PUBLISHED,
    allowDownloads: true,
    commentsEnabled: true,
    daysAgo: 1,
    durationSeconds: 29,
    baseFrequency: 174,
    pulseFrequency: 2.2,
    palette: { background: '#1f2937', foreground: '#fefce8', accent: '#f59e0b' },
  },
  {
    slug: 'southbound-lights',
    artistUsername: 'miko-lane',
    title: 'Southbound Lights',
    description:
      'A clean house sketch with clipped vocal chops and a bassline that keeps leaning forward.',
    genre: 'House',
    tags: ['club', 'night', 'dj-tool'],
    privacy: TrackPrivacy.PUBLIC,
    status: TrackStatus.PUBLISHED,
    allowDownloads: false,
    commentsEnabled: true,
    daysAgo: 5,
    durationSeconds: 14,
    baseFrequency: 247,
    pulseFrequency: 3.5,
    palette: { background: '#111827', foreground: '#ecfeff', accent: '#22d3ee' },
  },
  {
    slug: 'glass-circuit',
    artistUsername: 'miko-lane',
    title: 'Glass Circuit',
    description:
      'A longer house sketch with clean kick weight, clipped vocal air, and a steadier club-forward arc.',
    genre: 'House',
    tags: ['club', 'mix', 'groove'],
    privacy: TrackPrivacy.PUBLIC,
    status: TrackStatus.PUBLISHED,
    allowDownloads: false,
    commentsEnabled: true,
    daysAgo: 2,
    durationSeconds: 30,
    baseFrequency: 233,
    pulseFrequency: 3.2,
    palette: { background: '#0f172a', foreground: '#ecfeff', accent: '#67e8f9' },
  },
  {
    slug: 'soft-signal',
    artistUsername: 'noa-river',
    title: 'Soft Signal',
    description:
      'Subtle ambient swells and patient top notes built to leave space around a voiceover.',
    genre: 'Ambient',
    tags: ['ambient', 'focus', 'drift'],
    privacy: TrackPrivacy.PUBLIC,
    status: TrackStatus.PUBLISHED,
    allowDownloads: true,
    commentsEnabled: true,
    daysAgo: 7,
    durationSeconds: 20,
    baseFrequency: 164,
    pulseFrequency: 1.4,
    palette: { background: '#0f172a', foreground: '#e0f2fe', accent: '#38bdf8' },
  },
  {
    slug: 'blue-hour-tide',
    artistUsername: 'noa-river',
    title: 'Blue Hour Tide',
    description:
      'An extended ambient swell with slow-moving chords, a brighter upper shimmer, and a deeper low pulse.',
    genre: 'Ambient',
    tags: ['ambient', 'focus', 'shimmer'],
    privacy: TrackPrivacy.PUBLIC,
    status: TrackStatus.PUBLISHED,
    allowDownloads: true,
    commentsEnabled: true,
    daysAgo: 1,
    durationSeconds: 31,
    baseFrequency: 150,
    pulseFrequency: 1.5,
    palette: { background: '#082f49', foreground: '#e0f2fe', accent: '#22d3ee' },
  },
  {
    slug: 'afterimage',
    artistUsername: 'luka-bayne',
    title: 'Afterimage',
    description: 'An indie-pop scratch take with roomy drums and a chorus that lands immediately.',
    genre: 'Indie',
    tags: ['indie', 'hook', 'demo'],
    privacy: TrackPrivacy.PUBLIC,
    status: TrackStatus.PUBLISHED,
    allowDownloads: false,
    commentsEnabled: true,
    daysAgo: 9,
    durationSeconds: 17,
    baseFrequency: 208,
    pulseFrequency: 2.2,
    palette: { background: '#1c1917', foreground: '#fafaf9', accent: '#fb7185' },
  },
  {
    slug: 'paper-jetlag',
    artistUsername: 'luka-bayne',
    title: 'Paper Jetlag',
    description:
      'A longer indie demo with roomy drums, a brighter chorus, and a slower-blooming hook line.',
    genre: 'Indie',
    tags: ['indie', 'hook', 'demo'],
    privacy: TrackPrivacy.PUBLIC,
    status: TrackStatus.PUBLISHED,
    allowDownloads: false,
    commentsEnabled: true,
    daysAgo: 2,
    durationSeconds: 28,
    baseFrequency: 196,
    pulseFrequency: 2.4,
    palette: { background: '#111827', foreground: '#fafaf9', accent: '#f97316' },
  },
  {
    slug: 'tape-bloom',
    artistUsername: 'solis-kim',
    title: 'Tape Bloom',
    description:
      'A dusty loop-led beat with warm kick weight and enough room for a top line later.',
    genre: 'Hip-Hop',
    tags: ['dusty', 'loop', 'beats'],
    privacy: TrackPrivacy.PUBLIC,
    status: TrackStatus.PUBLISHED,
    allowDownloads: true,
    commentsEnabled: true,
    daysAgo: 4,
    durationSeconds: 15,
    baseFrequency: 180,
    pulseFrequency: 2.8,
    palette: { background: '#27272a', foreground: '#faf5ff', accent: '#f59e0b' },
  },
  {
    slug: 'velvet-runner',
    artistUsername: 'solis-kim',
    title: 'Velvet Runner',
    description:
      'A longer hip-hop sketch with a warm low end, dusty midrange, and enough room for a topline later.',
    genre: 'Hip-Hop',
    tags: ['beat', 'dusty', 'loop'],
    privacy: TrackPrivacy.PUBLIC,
    status: TrackStatus.PUBLISHED,
    allowDownloads: true,
    commentsEnabled: true,
    daysAgo: 0,
    durationSeconds: 30,
    baseFrequency: 180,
    pulseFrequency: 2.9,
    palette: { background: '#1f2937', foreground: '#faf5ff', accent: '#f59e0b' },
  },
  {
    slug: 'open-water-demo',
    artistUsername: 'aria-voss',
    title: 'Open Water Demo',
    description: 'Unlisted ambient guitar wash shared for close listeners and playlist editors.',
    genre: 'Ambient',
    tags: ['unlisted', 'guitar', 'wash'],
    privacy: TrackPrivacy.UNLISTED,
    status: TrackStatus.PUBLISHED,
    allowDownloads: false,
    commentsEnabled: true,
    daysAgo: 6,
    durationSeconds: 19,
    baseFrequency: 174,
    pulseFrequency: 1.8,
    palette: { background: '#082f49', foreground: '#ecfeff', accent: '#67e8f9' },
  },
  {
    slug: 'afterhours-hush',
    artistUsername: 'noa-river',
    title: 'Afterhours Hush',
    description:
      'An unlisted R&B sketch with a slower pocket, softer pad bed, and enough space for a topline.',
    genre: 'R&B',
    tags: ['unlisted', 'rnb', 'late-night'],
    privacy: TrackPrivacy.UNLISTED,
    status: TrackStatus.PUBLISHED,
    allowDownloads: false,
    commentsEnabled: true,
    daysAgo: 3,
    durationSeconds: 29,
    baseFrequency: 152,
    pulseFrequency: 1.9,
    palette: { background: '#2e1065', foreground: '#faf5ff', accent: '#c084fc' },
  },
  {
    slug: 'private-draft-session',
    artistUsername: 'miko-lane',
    title: 'Private Draft Session',
    description: 'A rough private build with kick placement ideas and a placeholder drop section.',
    genre: 'House',
    tags: ['draft', 'private', 'work-in-progress'],
    privacy: TrackPrivacy.PRIVATE,
    status: TrackStatus.DRAFT,
    allowDownloads: false,
    commentsEnabled: false,
    daysAgo: 3,
    durationSeconds: 13,
    baseFrequency: 192,
    pulseFrequency: 4,
    palette: { background: '#172554', foreground: '#eff6ff', accent: '#60a5fa' },
  },
  {
    slug: 'echo-relay',
    artistUsername: 'noa-river',
    title: 'Echo Relay',
    description:
      'Low-key R&B textures, clipped percussion, and just enough vocal room for a topline.',
    genre: 'R&B',
    tags: ['rnb', 'late-night', 'smooth'],
    privacy: TrackPrivacy.PUBLIC,
    status: TrackStatus.PUBLISHED,
    allowDownloads: true,
    commentsEnabled: true,
    daysAgo: 8,
    durationSeconds: 18,
    baseFrequency: 156,
    pulseFrequency: 2.1,
    palette: { background: '#2e1065', foreground: '#faf5ff', accent: '#c084fc' },
  },
  {
    slug: 'neon-courtyard',
    artistUsername: 'luka-bayne',
    title: 'Neon Courtyard',
    description: 'A bright top-line demo currently hidden while metadata is under review.',
    genre: 'Electronic',
    tags: ['hidden', 'demo', 'topline'],
    privacy: TrackPrivacy.PUBLIC,
    status: TrackStatus.HIDDEN,
    allowDownloads: false,
    commentsEnabled: true,
    hiddenReason: 'Hidden by moderation pending metadata review.',
    daysAgo: 12,
    durationSeconds: 16,
    baseFrequency: 230,
    pulseFrequency: 3.2,
    palette: { background: '#172554', foreground: '#fdf4ff', accent: '#f472b6' },
  },
  // ── New 18 tracks from new 5 creators ──────────────────────────────────
  {
    slug: 'river-soul',
    artistUsername: 'zara-nash',
    title: 'River Soul',
    description: 'A mid-tempo soul groove with warm brass stabs and a dusty Rhodes lead.',
    genre: 'Soul',
    tags: ['soul', 'groove', 'rhodes'],
    privacy: TrackPrivacy.PUBLIC,
    status: TrackStatus.PUBLISHED,
    allowDownloads: true,
    commentsEnabled: true,
    daysAgo: 3,
    durationSeconds: 24,
    baseFrequency: 188,
    pulseFrequency: 2.3,
    palette: { background: '#3d0000', foreground: '#fff3e0', accent: '#ff6b35' },
  },
  {
    slug: 'amber-dusk',
    artistUsername: 'zara-nash',
    title: 'Amber Dusk',
    description: 'Slow jazz chords over a walking bass — made in one take at golden hour.',
    genre: 'Jazz',
    tags: ['jazz', 'golden-hour', 'bass'],
    privacy: TrackPrivacy.PUBLIC,
    status: TrackStatus.PUBLISHED,
    allowDownloads: true,
    commentsEnabled: true,
    daysAgo: 6,
    durationSeconds: 27,
    baseFrequency: 176,
    pulseFrequency: 1.7,
    palette: { background: '#1a0000', foreground: '#ffd6b0', accent: '#ff9800' },
  },
  {
    slug: 'static-field',
    artistUsername: 'finn-oslo',
    title: 'Static Field',
    description:
      'Glitchy IDM with field-recorded rain, fragmented percussion, and slow melodic drift.',
    genre: 'Experimental',
    tags: ['idm', 'glitch', 'field-recording'],
    privacy: TrackPrivacy.PUBLIC,
    status: TrackStatus.PUBLISHED,
    allowDownloads: true,
    commentsEnabled: true,
    daysAgo: 4,
    durationSeconds: 22,
    baseFrequency: 262,
    pulseFrequency: 1.1,
    palette: { background: '#0a1628', foreground: '#e8f4f8', accent: '#00bcd4' },
  },
  {
    slug: 'ice-lattice',
    artistUsername: 'finn-oslo',
    title: 'Ice Lattice',
    description:
      'Modular synthesis with crystalline tones and long decay tails from a Nordic winter.',
    genre: 'Experimental',
    tags: ['modular', 'texture', 'nordic'],
    privacy: TrackPrivacy.PUBLIC,
    status: TrackStatus.PUBLISHED,
    allowDownloads: false,
    commentsEnabled: true,
    daysAgo: 11,
    durationSeconds: 33,
    baseFrequency: 280,
    pulseFrequency: 0.9,
    palette: { background: '#0d1b2a', foreground: '#e0f2f7', accent: '#26c6da' },
  },
  {
    slug: 'pastel-grid',
    artistUsername: 'cleo-wave',
    title: 'Pastel Grid',
    description:
      'Synth-pop with layered arpeggios, a tight snare, and a wide stereo chorus effect.',
    genre: 'Pop',
    tags: ['synth-pop', 'chorus', 'bright'],
    privacy: TrackPrivacy.PUBLIC,
    status: TrackStatus.PUBLISHED,
    allowDownloads: true,
    commentsEnabled: true,
    daysAgo: 1,
    durationSeconds: 20,
    baseFrequency: 294,
    pulseFrequency: 3.0,
    palette: { background: '#1a0033', foreground: '#f3e5ff', accent: '#b388ff' },
  },
  {
    slug: 'neon-bloom',
    artistUsername: 'cleo-wave',
    title: 'Neon Bloom',
    description: 'Upbeat bedroom indie with big reverb guitars and a hook that arrives early.',
    genre: 'Indie',
    tags: ['indie', 'bedroom', 'guitar'],
    privacy: TrackPrivacy.PUBLIC,
    status: TrackStatus.PUBLISHED,
    allowDownloads: true,
    commentsEnabled: true,
    daysAgo: 8,
    durationSeconds: 23,
    baseFrequency: 247,
    pulseFrequency: 2.7,
    palette: { background: '#12002a', foreground: '#ede7f6', accent: '#9c27b0' },
  },
  {
    slug: 'drop-zone',
    artistUsername: 'riku-jin',
    title: 'Drop Zone',
    description:
      'Future bass with a massive synth swell, sharp percussion, and a melodic lead on top.',
    genre: 'Future Bass',
    tags: ['future-bass', 'drop', 'melodic'],
    privacy: TrackPrivacy.PUBLIC,
    status: TrackStatus.PUBLISHED,
    allowDownloads: false,
    commentsEnabled: true,
    daysAgo: 2,
    durationSeconds: 18,
    baseFrequency: 311,
    pulseFrequency: 4.0,
    palette: { background: '#001a33', foreground: '#e3f2fd', accent: '#2196f3' },
  },
  {
    slug: 'trap-canvas',
    artistUsername: 'riku-jin',
    title: 'Trap Canvas',
    description: 'Lo-fi trap with a slow hi-hat swing, muted bass hits, and room for a verse.',
    genre: 'Hip-Hop',
    tags: ['trap', 'lo-fi', 'sketch'],
    privacy: TrackPrivacy.PUBLIC,
    status: TrackStatus.PUBLISHED,
    allowDownloads: true,
    commentsEnabled: true,
    daysAgo: 5,
    durationSeconds: 16,
    baseFrequency: 185,
    pulseFrequency: 2.5,
    palette: { background: '#000d1a', foreground: '#bbdefb', accent: '#1565c0' },
  },
  {
    slug: 'morning-chord',
    artistUsername: 'sena-sol',
    title: 'Morning Chord',
    description:
      'A quiet piano and double bass sketch — just an idea at 7am, recorded immediately.',
    genre: 'Jazz',
    tags: ['jazz', 'piano', 'sketch'],
    privacy: TrackPrivacy.PUBLIC,
    status: TrackStatus.PUBLISHED,
    allowDownloads: true,
    commentsEnabled: true,
    daysAgo: 3,
    durationSeconds: 21,
    baseFrequency: 196,
    pulseFrequency: 1.6,
    palette: { background: '#1b2200', foreground: '#f9fbe7', accent: '#c6e826' },
  },
  {
    slug: 'sunday-neo-soul',
    artistUsername: 'sena-sol',
    title: 'Sunday Neo-Soul',
    description: 'A neo-soul groove with warm organ chords, brushed snare, and a Rhodes melody.',
    genre: 'Soul',
    tags: ['neo-soul', 'organ', 'rhodes'],
    privacy: TrackPrivacy.PUBLIC,
    status: TrackStatus.PUBLISHED,
    allowDownloads: true,
    commentsEnabled: true,
    daysAgo: 7,
    durationSeconds: 26,
    baseFrequency: 174,
    pulseFrequency: 2.0,
    palette: { background: '#0d1400', foreground: '#f0f4c3', accent: '#aed136' },
  },
  {
    slug: 'coastal-drift',
    artistUsername: 'aria-voss',
    title: 'Coastal Drift',
    description: 'A gentle instrumental with acoustic layers and coastal field-recording ambience.',
    genre: 'Ambient',
    tags: ['acoustic', 'coastal', 'field-recording'],
    privacy: TrackPrivacy.PUBLIC,
    status: TrackStatus.PUBLISHED,
    allowDownloads: true,
    commentsEnabled: true,
    daysAgo: 14,
    durationSeconds: 25,
    baseFrequency: 164,
    pulseFrequency: 1.3,
    palette: { background: '#082f49', foreground: '#f0fdff', accent: '#38bdf8' },
  },
  {
    slug: 'depth-charge',
    artistUsername: 'miko-lane',
    title: 'Depth Charge',
    description: 'A rolling techno sketch with layered kick density and an acid bass lead.',
    genre: 'Techno',
    tags: ['techno', 'acid', 'dark'],
    privacy: TrackPrivacy.PUBLIC,
    status: TrackStatus.PUBLISHED,
    allowDownloads: false,
    commentsEnabled: true,
    daysAgo: 10,
    durationSeconds: 28,
    baseFrequency: 262,
    pulseFrequency: 4.2,
    palette: { background: '#0a0a0f', foreground: '#e0e0ff', accent: '#7c4dff' },
  },
  {
    slug: 'pulse-room',
    artistUsername: 'miko-lane',
    title: 'Pulse Room',
    description: 'A minimal techno sketch built on breath-like pads and a locked, hypnotic groove.',
    genre: 'Techno',
    tags: ['minimal', 'techno', 'hypnotic'],
    privacy: TrackPrivacy.PUBLIC,
    status: TrackStatus.PUBLISHED,
    allowDownloads: false,
    commentsEnabled: true,
    daysAgo: 15,
    durationSeconds: 32,
    baseFrequency: 247,
    pulseFrequency: 3.8,
    palette: { background: '#0f0f1a', foreground: '#e8e8ff', accent: '#6366f1' },
  },
  {
    slug: 'grid-walk',
    artistUsername: 'solis-kim',
    title: 'Grid Walk',
    description: 'A focused drum machine beat with a chromatic bass hook and subtle vinyl crackle.',
    genre: 'Electronic',
    tags: ['drum-machine', 'bass', 'vinyl'],
    privacy: TrackPrivacy.PUBLIC,
    status: TrackStatus.PUBLISHED,
    allowDownloads: true,
    commentsEnabled: true,
    daysAgo: 13,
    durationSeconds: 19,
    baseFrequency: 233,
    pulseFrequency: 2.4,
    palette: { background: '#111827', foreground: '#f8fafc', accent: '#a78bfa' },
  },
  {
    slug: 'drum-n-dub',
    artistUsername: 'luka-bayne',
    title: 'Drum & Dub',
    description: 'Fast half-step percussion with dub echo sends and a sub-bass movement.',
    genre: 'Drum & Bass',
    tags: ['dnb', 'dub', 'sub-bass'],
    privacy: TrackPrivacy.PUBLIC,
    status: TrackStatus.PUBLISHED,
    allowDownloads: false,
    commentsEnabled: true,
    daysAgo: 16,
    durationSeconds: 22,
    baseFrequency: 220,
    pulseFrequency: 5.5,
    palette: { background: '#1c1917', foreground: '#fafaf9', accent: '#f97316' },
  },
  {
    slug: 'slow-burn',
    artistUsername: 'noa-river',
    title: 'Slow Burn',
    description: 'A warm R&B ballad sketch with reverb-heavy piano and a deep sub-bass pulse.',
    genre: 'R&B',
    tags: ['rnb', 'ballad', 'piano'],
    privacy: TrackPrivacy.PUBLIC,
    status: TrackStatus.PUBLISHED,
    allowDownloads: true,
    commentsEnabled: true,
    daysAgo: 12,
    durationSeconds: 30,
    baseFrequency: 148,
    pulseFrequency: 1.6,
    palette: { background: '#1e0f2e', foreground: '#faf5ff', accent: '#d946ef' },
  },
  {
    slug: 'fog-machine',
    artistUsername: 'finn-oslo',
    title: 'Fog Machine',
    description:
      'Atmospheric electronics, processed drones and detuned oscillators in a minor key.',
    genre: 'Experimental',
    tags: ['drone', 'dark-ambient', 'modular'],
    privacy: TrackPrivacy.PUBLIC,
    status: TrackStatus.PUBLISHED,
    allowDownloads: true,
    commentsEnabled: true,
    daysAgo: 20,
    durationSeconds: 35,
    baseFrequency: 130,
    pulseFrequency: 0.7,
    palette: { background: '#0a1628', foreground: '#cfd8dc', accent: '#607d8b' },
  },
  {
    slug: 'pop-wave',
    artistUsername: 'cleo-wave',
    title: 'Pop Wave',
    description: 'A catchy synth-pop draft with a layered chorus and a brighter drop moment.',
    genre: 'Pop',
    tags: ['pop', 'catchy', 'chorus'],
    privacy: TrackPrivacy.PUBLIC,
    status: TrackStatus.PUBLISHED,
    allowDownloads: true,
    commentsEnabled: true,
    daysAgo: 18,
    durationSeconds: 21,
    baseFrequency: 330,
    pulseFrequency: 3.1,
    palette: { background: '#1a0033', foreground: '#ede7f6', accent: '#7b1fa2' },
  },
];

// ---------------------------------------------------------------------------
// Playlists — 4 original + 6 new = 10 total
// ---------------------------------------------------------------------------

export const SEED_PLAYLISTS: SeedPlaylistSpec[] = [
  {
    slug: 'night-shift-warmup',
    ownerUsername: 'ivy-hart',
    title: 'Night Shift Warmup',
    description: 'Warm loops and low-light grooves for late design passes and one more deploy.',
    isPublic: true,
    trackSlugs: [
      'aurora-current',
      'midnight-static',
      'blue-hour-tide',
      'soft-signal',
      'echo-relay',
    ],
    daysAgo: 1,
    palette: { background: '#111827', foreground: '#f9fafb', accent: '#fb7185' },
  },
  {
    slug: 'city-loop-reposts',
    ownerUsername: 'dev-patel',
    title: 'City Loop Reposts',
    description: 'The kind of repost chain that keeps a commute moving quickly.',
    isPublic: true,
    trackSlugs: ['glass-circuit', 'midnight-static', 'southbound-lights', 'paper-jetlag'],
    daysAgo: 2,
    palette: { background: '#0f172a', foreground: '#f8fafc', accent: '#38bdf8' },
  },
  {
    slug: 'sunday-edit-mode',
    ownerUsername: 'aria-voss',
    title: 'Sunday Edit Mode',
    description: 'My current folder of gentle textures, space, and a few near-finished ideas.',
    isPublic: true,
    trackSlugs: [
      'balcony-sunrise',
      'linen-hours',
      'afterimage',
      'open-water-demo',
      'afterhours-hush',
    ],
    daysAgo: 4,
    palette: { background: '#1f2937', foreground: '#fefce8', accent: '#f59e0b' },
  },
  {
    slug: 'skyline-commute',
    ownerUsername: 'mia-tran',
    title: 'Skyline Commute',
    description: 'Fast starts, polished hooks, and a little lift before the inbox opens.',
    isPublic: true,
    trackSlugs: ['balcony-sunrise', 'velvet-runner', 'southbound-lights', 'echo-relay'],
    daysAgo: 3,
    palette: { background: '#164e63', foreground: '#ecfeff', accent: '#67e8f9' },
  },
  {
    slug: 'late-night-focus',
    ownerUsername: 'emi-lake',
    title: 'Late Night Focus',
    description: 'Deep ambient and slow electronic for the final hours of a long session.',
    isPublic: true,
    trackSlugs: [
      'soft-signal',
      'blue-hour-tide',
      'static-field',
      'fog-machine',
      'slow-burn',
      'coastal-drift',
    ],
    daysAgo: 5,
    palette: { background: '#00192b', foreground: '#e8eaf6', accent: '#9fa8da' },
  },
  {
    slug: 'global-beats',
    ownerUsername: 'kai-brooks',
    title: 'Global Beats',
    description: 'Hip-hop, soul, and bass music from producers around the world.',
    isPublic: true,
    trackSlugs: [
      'tape-bloom',
      'velvet-runner',
      'river-soul',
      'trap-canvas',
      'drum-n-dub',
      'amber-dusk',
    ],
    daysAgo: 7,
    palette: { background: '#212121', foreground: '#fafafa', accent: '#ff5722' },
  },
  {
    slug: 'club-prep',
    ownerUsername: 'tobias-m',
    title: 'Club Prep',
    description: 'Techno and house demos to test in a room before they are finished.',
    isPublic: true,
    trackSlugs: ['depth-charge', 'pulse-room', 'glass-circuit', 'southbound-lights', 'drop-zone'],
    daysAgo: 2,
    palette: { background: '#111111', foreground: '#f5f5f5', accent: '#7c4dff' },
  },
  {
    slug: 'bedroom-indie-shelf',
    ownerUsername: 'nadia-berg',
    title: 'Bedroom Indie Shelf',
    description: 'Small, personal, and recorded with one microphone. A collection of rough gems.',
    isPublic: true,
    trackSlugs: ['neon-bloom', 'afterimage', 'paper-jetlag', 'pastel-grid', 'morning-chord'],
    daysAgo: 9,
    palette: { background: '#002233', foreground: '#e8f5e9', accent: '#66bb6a' },
  },
  {
    slug: 'producers-corner',
    ownerUsername: 'alex-wu',
    title: "Producer's Corner",
    description: 'Deconstructing production choices — what makes a track click.',
    isPublic: true,
    trackSlugs: ['grid-walk', 'aurora-current', 'drop-zone', 'ice-lattice', 'depth-charge'],
    daysAgo: 6,
    palette: { background: '#0d2137', foreground: '#e8eaf6', accent: '#7986cb' },
  },
  {
    slug: 'sunrise-sessions',
    ownerUsername: 'priya-sen',
    title: 'Sunrise Sessions',
    description: 'Easy, slow, and wide. Perfect for the first hour of the morning.',
    isPublic: true,
    trackSlugs: [
      'balcony-sunrise',
      'morning-chord',
      'sunday-neo-soul',
      'linen-hours',
      'coastal-drift',
    ],
    daysAgo: 8,
    palette: { background: '#1a0026', foreground: '#f3e5f5', accent: '#ce93d8' },
  },
];

// ---------------------------------------------------------------------------
// Social graph — follows, likes, reposts
// ---------------------------------------------------------------------------

export const SEED_FOLLOWS: Array<[string, string]> = [
  // Original follows
  ['ivy-hart', 'solis-kim'],
  ['ivy-hart', 'aria-voss'],
  ['dev-patel', 'miko-lane'],
  ['dev-patel', 'solis-kim'],
  ['mia-tran', 'aria-voss'],
  ['mia-tran', 'noa-river'],
  ['theo-cross', 'miko-lane'],
  ['theo-cross', 'luka-bayne'],
  ['jules-park', 'noa-river'],
  ['jules-park', 'solis-kim'],
  ['aria-voss', 'noa-river'],
  ['solis-kim', 'miko-lane'],
  // New follows — new listeners following creators
  ['kai-brooks', 'solis-kim'],
  ['kai-brooks', 'riku-jin'],
  ['kai-brooks', 'zara-nash'],
  ['luna-mar', 'aria-voss'],
  ['luna-mar', 'sena-sol'],
  ['luna-mar', 'noa-river'],
  ['sam-reed', 'finn-oslo'],
  ['sam-reed', 'luka-bayne'],
  ['alex-wu', 'riku-jin'],
  ['alex-wu', 'miko-lane'],
  ['alex-wu', 'finn-oslo'],
  ['priya-sen', 'sena-sol'],
  ['priya-sen', 'noa-river'],
  ['omar-diaz', 'solis-kim'],
  ['omar-diaz', 'zara-nash'],
  ['hana-kato', 'riku-jin'],
  ['hana-kato', 'cleo-wave'],
  ['hana-kato', 'aria-voss'],
  ['ben-flores', 'miko-lane'],
  ['ben-flores', 'luka-bayne'],
  ['nadia-berg', 'cleo-wave'],
  ['nadia-berg', 'luka-bayne'],
  ['carlos-rey', 'miko-lane'],
  ['carlos-rey', 'finn-oslo'],
  ['emi-lake', 'noa-river'],
  ['emi-lake', 'finn-oslo'],
  ['emi-lake', 'aria-voss'],
  ['leo-hart', 'solis-kim'],
  ['leo-hart', 'zara-nash'],
  ['leo-hart', 'finn-oslo'],
  ['yui-chen', 'cleo-wave'],
  ['yui-chen', 'riku-jin'],
  ['tobias-m', 'miko-lane'],
  ['tobias-m', 'finn-oslo'],
  ['aisha-ko', 'zara-nash'],
  ['aisha-ko', 'sena-sol'],
  ['aisha-ko', 'aria-voss'],
  // New creators following each other
  ['zara-nash', 'sena-sol'],
  ['zara-nash', 'noa-river'],
  ['finn-oslo', 'solis-kim'],
  ['cleo-wave', 'aria-voss'],
  ['cleo-wave', 'luka-bayne'],
  ['riku-jin', 'miko-lane'],
  ['riku-jin', 'finn-oslo'],
  ['sena-sol', 'zara-nash'],
  ['sena-sol', 'noa-river'],
  ['luka-bayne', 'cleo-wave'],
  ['noa-river', 'sena-sol'],
  ['miko-lane', 'riku-jin'],
];

export const SEED_LIKES: Array<[string, string]> = [
  // Original likes
  ['ivy-hart', 'midnight-static'],
  ['ivy-hart', 'soft-signal'],
  ['ivy-hart', 'aurora-current'],
  ['dev-patel', 'southbound-lights'],
  ['dev-patel', 'midnight-static'],
  ['dev-patel', 'glass-circuit'],
  ['mia-tran', 'balcony-sunrise'],
  ['mia-tran', 'echo-relay'],
  ['mia-tran', 'blue-hour-tide'],
  ['theo-cross', 'southbound-lights'],
  ['theo-cross', 'afterimage'],
  ['theo-cross', 'velvet-runner'],
  ['jules-park', 'soft-signal'],
  ['jules-park', 'balcony-sunrise'],
  ['jules-park', 'paper-jetlag'],
  ['aria-voss', 'soft-signal'],
  ['solis-kim', 'afterimage'],
  // New likes
  ['kai-brooks', 'tape-bloom'],
  ['kai-brooks', 'velvet-runner'],
  ['kai-brooks', 'river-soul'],
  ['kai-brooks', 'trap-canvas'],
  ['luna-mar', 'soft-signal'],
  ['luna-mar', 'blue-hour-tide'],
  ['luna-mar', 'coastal-drift'],
  ['luna-mar', 'morning-chord'],
  ['sam-reed', 'static-field'],
  ['sam-reed', 'fog-machine'],
  ['sam-reed', 'ice-lattice'],
  ['alex-wu', 'drop-zone'],
  ['alex-wu', 'grid-walk'],
  ['alex-wu', 'depth-charge'],
  ['priya-sen', 'morning-chord'],
  ['priya-sen', 'sunday-neo-soul'],
  ['priya-sen', 'soft-signal'],
  ['omar-diaz', 'tape-bloom'],
  ['omar-diaz', 'river-soul'],
  ['omar-diaz', 'amber-dusk'],
  ['hana-kato', 'pastel-grid'],
  ['hana-kato', 'drop-zone'],
  ['hana-kato', 'neon-bloom'],
  ['ben-flores', 'glass-circuit'],
  ['ben-flores', 'depth-charge'],
  ['ben-flores', 'southbound-lights'],
  ['nadia-berg', 'neon-bloom'],
  ['nadia-berg', 'afterimage'],
  ['nadia-berg', 'paper-jetlag'],
  ['carlos-rey', 'glass-circuit'],
  ['carlos-rey', 'pulse-room'],
  ['carlos-rey', 'drum-n-dub'],
  ['emi-lake', 'soft-signal'],
  ['emi-lake', 'fog-machine'],
  ['emi-lake', 'blue-hour-tide'],
  ['leo-hart', 'aurora-current'],
  ['leo-hart', 'amber-dusk'],
  ['leo-hart', 'river-soul'],
  ['yui-chen', 'pastel-grid'],
  ['yui-chen', 'pop-wave'],
  ['yui-chen', 'neon-bloom'],
  ['tobias-m', 'depth-charge'],
  ['tobias-m', 'pulse-room'],
  ['tobias-m', 'static-field'],
  ['aisha-ko', 'sunday-neo-soul'],
  ['aisha-ko', 'river-soul'],
  ['aisha-ko', 'amber-dusk'],
  ['zara-nash', 'morning-chord'],
  ['finn-oslo', 'static-field'],
  ['cleo-wave', 'pastel-grid'],
  ['riku-jin', 'drop-zone'],
  ['sena-sol', 'amber-dusk'],
  ['miko-lane', 'depth-charge'],
  ['noa-river', 'soft-signal'],
  ['luka-bayne', 'drum-n-dub'],
  ['solis-kim', 'grid-walk'],
];

export const SEED_REPOSTS: Array<[string, string]> = [
  // Original reposts
  ['ivy-hart', 'midnight-static'],
  ['ivy-hart', 'aurora-current'],
  ['dev-patel', 'southbound-lights'],
  ['dev-patel', 'glass-circuit'],
  ['mia-tran', 'balcony-sunrise'],
  ['mia-tran', 'blue-hour-tide'],
  ['theo-cross', 'southbound-lights'],
  ['theo-cross', 'velvet-runner'],
  ['jules-park', 'soft-signal'],
  ['aria-voss', 'echo-relay'],
  // New reposts
  ['kai-brooks', 'velvet-runner'],
  ['kai-brooks', 'river-soul'],
  ['luna-mar', 'coastal-drift'],
  ['sam-reed', 'fog-machine'],
  ['alex-wu', 'depth-charge'],
  ['priya-sen', 'sunday-neo-soul'],
  ['omar-diaz', 'amber-dusk'],
  ['hana-kato', 'drop-zone'],
  ['ben-flores', 'glass-circuit'],
  ['nadia-berg', 'neon-bloom'],
  ['carlos-rey', 'drum-n-dub'],
  ['emi-lake', 'soft-signal'],
  ['leo-hart', 'aurora-current'],
  ['yui-chen', 'pop-wave'],
  ['tobias-m', 'pulse-room'],
  ['aisha-ko', 'river-soul'],
  ['zara-nash', 'morning-chord'],
  ['cleo-wave', 'neon-bloom'],
  ['riku-jin', 'trap-canvas'],
  ['sena-sol', 'sunday-neo-soul'],
];

// ---------------------------------------------------------------------------
// Comments — 13 original + 80+ new = ~95 total, realistic density
// ---------------------------------------------------------------------------

export const SEED_COMMENTS: SeedCommentSpec[] = [
  // ── midnight-static ──────────────────────────────────────────────────
  {
    key: 'midnight-static-c1',
    username: 'ivy-hart',
    trackSlug: 'midnight-static',
    body: 'The bass bloom around 1:06 is perfect for late work sessions.',
    timestampSeconds: 66,
  },
  {
    key: 'midnight-static-r1',
    username: 'solis-kim',
    trackSlug: 'midnight-static',
    parentKey: 'midnight-static-c1',
    body: 'Love that spot too. It came from a cassette delay bounce.',
  },
  {
    key: 'midnight-static-c2',
    username: 'dev-patel',
    trackSlug: 'midnight-static',
    body: 'This just became my default coding track. The tempo is exactly right.',
    timestampSeconds: 12,
  },
  {
    key: 'midnight-static-c3',
    username: 'leo-hart',
    trackSlug: 'midnight-static',
    body: "The pads have this slow bloom quality that's hard to nail. Really clean execution.",
    timestampSeconds: 48,
  },
  {
    key: 'midnight-static-c4',
    username: 'kai-brooks',
    trackSlug: 'midnight-static',
    body: 'Short but complete. This is the whole idea fully expressed.',
  },

  // ── aurora-current ───────────────────────────────────────────────────
  {
    key: 'aurora-c1',
    username: 'dev-patel',
    trackSlug: 'aurora-current',
    body: 'This one has the longest, cleanest glide in the whole set.',
    timestampSeconds: 41,
  },
  {
    key: 'aurora-c2',
    username: 'ivy-hart',
    trackSlug: 'aurora-current',
    body: 'Feels like a sequel to Midnight Static. The harmonic drift is satisfying.',
    timestampSeconds: 18,
  },
  {
    key: 'aurora-c3',
    username: 'leo-hart',
    trackSlug: 'aurora-current',
    body: 'This is what late-night electronic should sound like. Patient and full.',
    timestampSeconds: 22,
  },
  {
    key: 'aurora-c4',
    username: 'emi-lake',
    trackSlug: 'aurora-current',
    body: 'The way the harmonics drift in at the end makes this feel twice as long — in a good way.',
  },
  {
    key: 'aurora-r1',
    username: 'solis-kim',
    trackSlug: 'aurora-current',
    parentKey: 'aurora-c4',
    body: 'That was exactly the target feeling. Glad it lands!',
  },
  {
    key: 'aurora-c5',
    username: 'sam-reed',
    trackSlug: 'aurora-current',
    body: 'Could score a film with this. The restraint is the whole point.',
    timestampSeconds: 29,
  },

  // ── balcony-sunrise ──────────────────────────────────────────────────
  {
    key: 'balcony-c1',
    username: 'mia-tran',
    trackSlug: 'balcony-sunrise',
    body: 'This feels like the exact first half-hour before the city wakes up.',
    timestampSeconds: 22,
  },
  {
    key: 'balcony-c2',
    username: 'jules-park',
    trackSlug: 'balcony-sunrise',
    body: 'That tape saturation on the drums is exactly the warmth I was looking for.',
  },
  {
    key: 'balcony-c3',
    username: 'luna-mar',
    trackSlug: 'balcony-sunrise',
    body: 'In my morning playlist permanently. Nothing else has this slow lift.',
    timestampSeconds: 8,
  },
  {
    key: 'balcony-c4',
    username: 'priya-sen',
    trackSlug: 'balcony-sunrise',
    body: 'The brush detail is so light — this is what I needed for a yoga playlist.',
    timestampSeconds: 14,
  },
  {
    key: 'balcony-r1',
    username: 'aria-voss',
    trackSlug: 'balcony-sunrise',
    parentKey: 'balcony-c4',
    body: 'So glad. That brush took three takes to get exactly right.',
  },
  {
    key: 'balcony-c5',
    username: 'aisha-ko',
    trackSlug: 'balcony-sunrise',
    body: "This is the kind of lo-fi that doesn't feel lazy. There's real intent here.",
  },

  // ── linen-hours ──────────────────────────────────────────────────────
  {
    key: 'linen-c1',
    username: 'jules-park',
    trackSlug: 'linen-hours',
    body: 'Soft, warm, and just long enough to keep focus locked in.',
    timestampSeconds: 19,
  },
  {
    key: 'linen-c2',
    username: 'luna-mar',
    trackSlug: 'linen-hours',
    body: 'Every study session this week. The widened chords breathe differently.',
  },
  {
    key: 'linen-c3',
    username: 'priya-sen',
    trackSlug: 'linen-hours',
    body: "There's something about the stereo width here that feels like open space.",
    timestampSeconds: 11,
  },

  // ── southbound-lights ────────────────────────────────────────────────
  {
    key: 'southbound-c1',
    username: 'theo-cross',
    trackSlug: 'southbound-lights',
    body: 'Kick and bass are glued nicely. Would love a longer drop here.',
    timestampSeconds: 44,
  },
  {
    key: 'southbound-c2',
    username: 'ben-flores',
    trackSlug: 'southbound-lights',
    body: 'The vocal chop sits perfectly in the groove. Classic house move.',
    timestampSeconds: 31,
  },
  {
    key: 'southbound-c3',
    username: 'carlos-rey',
    trackSlug: 'southbound-lights',
    body: 'Those kick transients are crisp without being too sharp. Mixing is tight.',
  },
  {
    key: 'southbound-hidden',
    username: 'theo-cross',
    trackSlug: 'southbound-lights',
    body: 'Removed by moderation after being flagged during demo seeding.',
    hidden: true,
  },
  {
    key: 'southbound-r1',
    username: 'miko-lane',
    trackSlug: 'southbound-lights',
    parentKey: 'southbound-c1',
    body: 'Longer version is in the works. Wanted to nail the foundation first.',
  },

  // ── glass-circuit ─────────────────────────────────────────────────────
  {
    key: 'glass-c1',
    username: 'theo-cross',
    trackSlug: 'glass-circuit',
    body: 'That low-end shape is nice and full without feeling crowded.',
    timestampSeconds: 33,
  },
  {
    key: 'glass-c2',
    username: 'dev-patel',
    trackSlug: 'glass-circuit',
    body: "The arc on this one is really satisfying. I'm waiting for a full version.",
    timestampSeconds: 15,
  },
  {
    key: 'glass-c3',
    username: 'tobias-m',
    trackSlug: 'glass-circuit',
    body: 'Would work in a room. That vocal air is a nice texture in the midrange.',
  },
  {
    key: 'glass-c4',
    username: 'carlos-rey',
    trackSlug: 'glass-circuit',
    body: 'This style of house is underrated. Tight, functional, but not boring.',
    timestampSeconds: 22,
  },

  // ── soft-signal ──────────────────────────────────────────────────────
  {
    key: 'soft-c1',
    username: 'jules-park',
    trackSlug: 'soft-signal',
    body: 'Instant focus soundtrack. The space in the top end is really clean.',
    timestampSeconds: 51,
  },
  {
    key: 'soft-c2',
    username: 'emi-lake',
    trackSlug: 'soft-signal',
    body: 'The negative space is the whole track. Very intentional.',
  },
  {
    key: 'soft-c3',
    username: 'luna-mar',
    trackSlug: 'soft-signal',
    body: 'My default background track for reading. It disappears without disappearing.',
    timestampSeconds: 14,
  },
  {
    key: 'soft-r1',
    username: 'noa-river',
    trackSlug: 'soft-signal',
    parentKey: 'soft-c2',
    body: 'That was the entire brief I gave myself. Glad you noticed.',
  },
  {
    key: 'soft-c4',
    username: 'priya-sen',
    trackSlug: 'soft-signal',
    body: 'Perfect for slow mornings. I use this more than any other track here.',
  },

  // ── blue-hour-tide ────────────────────────────────────────────────────
  {
    key: 'blue-c1',
    username: 'jules-park',
    trackSlug: 'blue-hour-tide',
    body: 'Perfect for a late edit session. The shimmer sits really well on top.',
    timestampSeconds: 52,
  },
  {
    key: 'blue-c2',
    username: 'emi-lake',
    trackSlug: 'blue-hour-tide',
    body: 'The sub pulse on this is barely there but completely changes the feel.',
    timestampSeconds: 18,
  },
  {
    key: 'blue-c3',
    username: 'luna-mar',
    trackSlug: 'blue-hour-tide',
    body: 'This is the best thing for long writing sessions. The shimmer keeps it present.',
  },
  {
    key: 'blue-c4',
    username: 'sam-reed',
    trackSlug: 'blue-hour-tide',
    body: "The way those slow chords evolve — it's cinematic without trying to be.",
    timestampSeconds: 27,
  },

  // ── afterimage ────────────────────────────────────────────────────────
  {
    key: 'afterimage-c1',
    username: 'nadia-berg',
    trackSlug: 'afterimage',
    body: 'That chorus hook is immediate. I was in before it even finished the first time.',
    timestampSeconds: 22,
  },
  {
    key: 'afterimage-c2',
    username: 'dev-patel',
    trackSlug: 'afterimage',
    body: 'The drum room on this is perfectly sized — big but not overproduced.',
  },
  {
    key: 'afterimage-c3',
    username: 'leo-hart',
    trackSlug: 'afterimage',
    body: 'This sounds like it could be on a playlist with early Bon Iver demos.',
    timestampSeconds: 9,
  },
  {
    key: 'afterimage-c4',
    username: 'solis-kim',
    trackSlug: 'afterimage',
    body: 'The hook rhythm is the thing. It hits every time.',
  },

  // ── paper-jetlag ──────────────────────────────────────────────────────
  {
    key: 'paper-c1',
    username: 'ivy-hart',
    trackSlug: 'paper-jetlag',
    body: 'The chorus lift arrives at exactly the right moment.',
    timestampSeconds: 26,
  },
  {
    key: 'paper-c2',
    username: 'nadia-berg',
    trackSlug: 'paper-jetlag',
    body: 'Longer than Afterimage but worth every second. Great build.',
  },
  {
    key: 'paper-c3',
    username: 'hana-kato',
    trackSlug: 'paper-jetlag',
    body: 'The sonic space is wide here. Feels produced without sounding polished.',
    timestampSeconds: 20,
  },

  // ── tape-bloom ────────────────────────────────────────────────────────
  {
    key: 'tape-c1',
    username: 'kai-brooks',
    trackSlug: 'tape-bloom',
    body: "That dusty kick is giving me nostalgia for beat tapes I can't find anymore.",
    timestampSeconds: 7,
  },
  {
    key: 'tape-c2',
    username: 'omar-diaz',
    trackSlug: 'tape-bloom',
    body: 'Simple, looped, honest. This is the kind of beat that stays with you.',
  },
  {
    key: 'tape-r1',
    username: 'solis-kim',
    trackSlug: 'tape-bloom',
    parentKey: 'tape-c2',
    body: 'Exactly the vibe I was after. No overthinking.',
  },

  // ── velvet-runner ─────────────────────────────────────────────────────
  {
    key: 'velvet-c1',
    username: 'mia-tran',
    trackSlug: 'velvet-runner',
    body: 'This feels like the most playlist-ready beat in the new batch.',
    timestampSeconds: 29,
  },
  {
    key: 'velvet-c2',
    username: 'kai-brooks',
    trackSlug: 'velvet-runner',
    body: 'The low-end warmth on the full version is so satisfying. Proper boom-bap feel.',
  },
  {
    key: 'velvet-c3',
    username: 'omar-diaz',
    trackSlug: 'velvet-runner',
    body: 'I hear a topline already. This is waiting for a verse.',
    timestampSeconds: 15,
  },

  // ── echo-relay ────────────────────────────────────────────────────────
  {
    key: 'echo-c1',
    username: 'dev-patel',
    trackSlug: 'echo-relay',
    body: 'Super smooth pocket. This would slide into a commute playlist immediately.',
    timestampSeconds: 37,
  },
  {
    key: 'echo-c2',
    username: 'mia-tran',
    trackSlug: 'echo-relay',
    body: 'Low-key and self-contained. R&B done right.',
  },
  {
    key: 'echo-c3',
    username: 'aisha-ko',
    trackSlug: 'echo-relay',
    body: 'The clipped percussion has a very specific texture. Interesting choice.',
    timestampSeconds: 9,
  },

  // ── river-soul ────────────────────────────────────────────────────────
  {
    key: 'river-c1',
    username: 'omar-diaz',
    trackSlug: 'river-soul',
    body: 'The Rhodes and brass together is a rare combo that actually works here.',
    timestampSeconds: 18,
  },
  {
    key: 'river-c2',
    username: 'aisha-ko',
    trackSlug: 'river-soul',
    body: "This has a depth that doesn't announce itself. Soul music at its best.",
  },
  {
    key: 'river-c3',
    username: 'leo-hart',
    trackSlug: 'river-soul',
    body: "I didn't expect the brass stab at 0:30. It changed everything.",
    timestampSeconds: 30,
  },
  {
    key: 'river-r1',
    username: 'zara-nash',
    trackSlug: 'river-soul',
    parentKey: 'river-c3',
    body: 'That stab was the last thing I added. Debated cutting it three times.',
  },

  // ── amber-dusk ───────────────────────────────────────────────────────
  {
    key: 'amber-c1',
    username: 'priya-sen',
    trackSlug: 'amber-dusk',
    body: "This jazz sketch is the most relaxed thing I've heard all week.",
    timestampSeconds: 12,
  },
  {
    key: 'amber-c2',
    username: 'sena-sol',
    trackSlug: 'amber-dusk',
    body: 'The walking bass has excellent pocket. Clean and unhurried.',
  },
  {
    key: 'amber-c3',
    username: 'omar-diaz',
    trackSlug: 'amber-dusk',
    body: 'One take jazz energy. I can hear it was recorded in the moment.',
    timestampSeconds: 8,
  },

  // ── static-field ─────────────────────────────────────────────────────
  {
    key: 'static-c1',
    username: 'sam-reed',
    trackSlug: 'static-field',
    body: 'The field-recorded rain makes everything else click into place.',
    timestampSeconds: 25,
  },
  {
    key: 'static-c2',
    username: 'tobias-m',
    trackSlug: 'static-field',
    body: "Unexpected and precise. IDM that doesn't feel academic.",
  },
  {
    key: 'static-r1',
    username: 'finn-oslo',
    trackSlug: 'static-field',
    parentKey: 'static-c1',
    body: 'Recorded during a January storm. No studio could replicate it.',
  },

  // ── ice-lattice ───────────────────────────────────────────────────────
  {
    key: 'ice-c1',
    username: 'emi-lake',
    trackSlug: 'ice-lattice',
    body: 'The decay tails on these tones are genuinely beautiful.',
    timestampSeconds: 14,
  },
  {
    key: 'ice-c2',
    username: 'alex-wu',
    trackSlug: 'ice-lattice',
    body: 'I want to know every patch setting on this modular setup.',
  },
  {
    key: 'ice-c3',
    username: 'sam-reed',
    trackSlug: 'ice-lattice',
    body: 'Crystalline is exactly the right word. It sounds frozen in the best way.',
    timestampSeconds: 28,
  },

  // ── pastel-grid ───────────────────────────────────────────────────────
  {
    key: 'pastel-c1',
    username: 'hana-kato',
    trackSlug: 'pastel-grid',
    body: 'That synth arpeggio is stuck in my head since the first listen.',
    timestampSeconds: 7,
  },
  {
    key: 'pastel-c2',
    username: 'yui-chen',
    trackSlug: 'pastel-grid',
    body: 'The stereo chorus effect is wide without feeling panned too hard.',
  },
  {
    key: 'pastel-r1',
    username: 'cleo-wave',
    trackSlug: 'pastel-grid',
    parentKey: 'pastel-c2',
    body: 'Spent a long time on that width balance. Thank you for noticing.',
  },
  {
    key: 'pastel-c3',
    username: 'nadia-berg',
    trackSlug: 'pastel-grid',
    body: 'This is exactly the kind of synth-pop that made me love the genre.',
    timestampSeconds: 15,
  },

  // ── drop-zone ─────────────────────────────────────────────────────────
  {
    key: 'drop-c1',
    username: 'hana-kato',
    trackSlug: 'drop-zone',
    body: 'That swell before the drop is physically satisfying.',
    timestampSeconds: 14,
  },
  {
    key: 'drop-c2',
    username: 'alex-wu',
    trackSlug: 'drop-zone',
    body: 'The melodic lead on top of the drop is what separates this from generic future bass.',
  },
  {
    key: 'drop-c3',
    username: 'kai-brooks',
    trackSlug: 'drop-zone',
    body: 'Clean production. The sidechain is working but not obvious.',
    timestampSeconds: 10,
  },

  // ── morning-chord ─────────────────────────────────────────────────────
  {
    key: 'morning-c1',
    username: 'priya-sen',
    trackSlug: 'morning-chord',
    body: 'A piano sketch this early in the morning and this quiet — perfect.',
    timestampSeconds: 6,
  },
  {
    key: 'morning-c2',
    username: 'luna-mar',
    trackSlug: 'morning-chord',
    body: "The double bass is warm and present but doesn't overpower the piano.",
  },
  {
    key: 'morning-r1',
    username: 'sena-sol',
    trackSlug: 'morning-chord',
    parentKey: 'morning-c2',
    body: 'That balance took a few mic adjustments. So glad the warmth came through.',
  },

  // ── sunday-neo-soul ───────────────────────────────────────────────────
  {
    key: 'sunday-c1',
    username: 'aisha-ko',
    trackSlug: 'sunday-neo-soul',
    body: 'The organ and Rhodes together at the start is everything.',
    timestampSeconds: 3,
  },
  {
    key: 'sunday-c2',
    username: 'priya-sen',
    trackSlug: 'sunday-neo-soul',
    body: 'I added this to my Sunday playlist five minutes after my first listen.',
  },
  {
    key: 'sunday-c3',
    username: 'omar-diaz',
    trackSlug: 'sunday-neo-soul',
    body: 'The brushed snare is classic neo-soul. Real craft here.',
    timestampSeconds: 18,
  },

  // ── depth-charge ─────────────────────────────────────────────────────
  {
    key: 'depth-c1',
    username: 'tobias-m',
    trackSlug: 'depth-charge',
    body: 'The acid lead is perfectly filthy. Modulating at exactly the right rate.',
    timestampSeconds: 22,
  },
  {
    key: 'depth-c2',
    username: 'carlos-rey',
    trackSlug: 'depth-charge',
    body: 'The kick density on this is serious. Mixed with a lot of room.',
  },
  {
    key: 'depth-c3',
    username: 'alex-wu',
    trackSlug: 'depth-charge',
    body: 'Layer count here is impressive. It feels dense without getting muddy.',
    timestampSeconds: 15,
  },

  // ── grid-walk ─────────────────────────────────────────────────────────
  {
    key: 'grid-c1',
    username: 'alex-wu',
    trackSlug: 'grid-walk',
    body: 'That chromatic bass hook is clever. I keep hearing new intervals.',
    timestampSeconds: 11,
  },
  {
    key: 'grid-c2',
    username: 'kai-brooks',
    trackSlug: 'grid-walk',
    body: 'The vinyl crackle underneath is subtle and exactly right.',
  },
  {
    key: 'grid-r1',
    username: 'solis-kim',
    trackSlug: 'grid-walk',
    parentKey: 'grid-c2',
    body: "Had to resist turning it up. It's supposed to just breathe under the kick.",
  },

  // ── slow-burn ─────────────────────────────────────────────────────────
  {
    key: 'slow-c1',
    username: 'emi-lake',
    trackSlug: 'slow-burn',
    body: "The reverb on this piano doesn't feel applied — it feels like the room.",
    timestampSeconds: 9,
  },
  {
    key: 'slow-c2',
    username: 'aisha-ko',
    trackSlug: 'slow-burn',
    body: 'That sub-bass underneath the piano is doing heavy lifting quietly.',
  },
];

// ---------------------------------------------------------------------------
// Reports
// ---------------------------------------------------------------------------

export const SEED_REPORTS: SeedReportSpec[] = [
  {
    reporterUsername: 'mia-tran',
    reportableType: ReportableType.TRACK,
    targetKey: 'southbound-lights',
    reason: 'Potential metadata mismatch',
    details: 'The upload title and description look slightly out of sync.',
    status: ReportStatus.PENDING,
  },
  {
    reporterUsername: 'ivy-hart',
    reportableType: ReportableType.COMMENT,
    targetKey: 'southbound-hidden',
    reason: 'Spam / low-signal comment',
    details: 'This comment looked like a throwaway placeholder.',
    status: ReportStatus.REVIEWED,
    resolvedByAdmin: true,
    resolutionNote: 'Confirmed and hidden by moderation.',
  },
  {
    reporterUsername: 'jules-park',
    reportableType: ReportableType.PLAYLIST,
    targetKey: 'city-loop-reposts',
    reason: 'Playlist description looks outdated',
    details: 'No harmful content, just checking moderation flow.',
    status: ReportStatus.DISMISSED,
    resolvedByAdmin: true,
    resolutionNote: 'Dismissed as non-actionable.',
  },
  {
    reporterUsername: 'emi-lake',
    reportableType: ReportableType.TRACK,
    targetKey: 'neon-courtyard',
    reason: 'Incomplete metadata',
    details: 'Genre and tags look inconsistent with the actual content.',
    status: ReportStatus.REVIEWED,
    resolvedByAdmin: true,
    resolutionNote: 'Track hidden pending creator update.',
  },
];

// ---------------------------------------------------------------------------
// Audit logs
// ---------------------------------------------------------------------------

export const SEED_AUDIT_LOGS: SeedAuditLogSpec[] = [
  {
    action: AdminActionType.HIDE_TRACK,
    entityType: 'track',
    entityKey: 'neon-courtyard',
    details: { reason: 'Hidden by moderation pending metadata review.' },
  },
  {
    action: AdminActionType.HIDE_COMMENT,
    entityType: 'comment',
    entityKey: 'southbound-hidden',
    details: { reason: 'Confirmed low-signal demo comment.' },
  },
];

// ---------------------------------------------------------------------------
// Notifications
// ---------------------------------------------------------------------------

export const SEED_NOTIFICATIONS: SeedNotificationSpec[] = [
  {
    username: 'solis-kim',
    type: NotificationType.FOLLOW,
    data: { username: 'ivy-hart', userId: 'ivy-hart' },
  },
  {
    username: 'aria-voss',
    type: NotificationType.LIKE,
    data: { username: 'mia-tran', trackSlug: 'balcony-sunrise' },
  },
  {
    username: 'miko-lane',
    type: NotificationType.REPOST,
    data: { username: 'dev-patel', trackSlug: 'southbound-lights' },
  },
  {
    username: 'noa-river',
    type: NotificationType.COMMENT,
    data: { username: 'jules-park', trackSlug: 'soft-signal' },
  },
  {
    username: 'ivy-hart',
    type: NotificationType.REPORT_UPDATE,
    data: { reportKey: 'southbound-hidden', status: ReportStatus.REVIEWED },
  },
  {
    username: 'zara-nash',
    type: NotificationType.FOLLOW,
    data: { username: 'aisha-ko', userId: 'aisha-ko' },
  },
  {
    username: 'zara-nash',
    type: NotificationType.LIKE,
    data: { username: 'leo-hart', trackSlug: 'river-soul' },
  },
  {
    username: 'finn-oslo',
    type: NotificationType.COMMENT,
    data: { username: 'sam-reed', trackSlug: 'static-field' },
  },
  {
    username: 'cleo-wave',
    type: NotificationType.LIKE,
    data: { username: 'hana-kato', trackSlug: 'pastel-grid' },
  },
  {
    username: 'riku-jin',
    type: NotificationType.COMMENT,
    data: { username: 'kai-brooks', trackSlug: 'drop-zone' },
  },
  {
    username: 'sena-sol',
    type: NotificationType.FOLLOW,
    data: { username: 'priya-sen', userId: 'priya-sen' },
  },
  {
    username: 'luka-bayne',
    type: NotificationType.LIKE,
    data: { username: 'nadia-berg', trackSlug: 'afterimage' },
  },
];
